apiVersion: v1
kind: Service
metadata:
  name: hazelcast-managment-service
spec:
  selector:
    app: hazelcast-managment-app
  ports:
    - port: 32772
      targetPort: 32772
      nodePort: 30245
  type: LoadBalancer